stages:          # List of stages for jobs, and their order of execution
  - build
  - doc

build-job:
    stage: build
    image: registry.mygit.th-deg.de/lois/ros/docker:latest

    script:
        - source /opt/ros/melodic/setup.bash
        - cd ../
        - mkdir -p ~/catkin_ws/src
        - cp -r $CI_PROJECT_NAME ~/catkin_ws/src
        - cd ~/catkin_ws
        - catkin_make -j1 -DCUDAOFF=ON

doxygen:
    stage: doc
    image: registry.mygit.th-deg.de/lois/ros/docker:latest
    
    script:
        - doxygen 
        - ls

    artifacts:
        paths:
            - "doc/html/**"
    cache:
        paths:
            - "doc/latex/**"
            - "doc/xml/**"
            - "doc/html/**"
        
latex:
    stage: doc
    image: registry.mygit.th-deg.de/textools/streeker:latest
    needs: 
        job: doxygen

    script:
        - ls
        - cd doc/latex
        - ls
        - latexmk -pdf refman.tex
        - mv refman.pdf $CI_PROJECT_NAME.pdf

    cache:
        paths:
            - "doc/latex/**"
            
    artifacts:
        paths:
            - "doc/latex/*.pdf"
